import { z } from "zod";

const envSchema = z.object({
  EXPO_PUBLIC_STORE_DOMAIN: z.string().min(1),
  EXPO_PUBLIC_STORE_TOKEN: z.string().min(1),
  EXPO_PUBLIC_ENCRYPTION_KEY: z.string().min(1),
  EXPO_PUBLIC_CUSTOMER_STORE_ENDPOINT: z.string().url(),
  EXPO_PUBLIC_CUSTOMER_ACCOUNT_API_TOKEN: z.string().min(1),
  EXPO_PUBLIC_CUSTOMER_ACCOUNT_API_ENDPOINT: z.string().url(),
  EXPO_PUBLIC_CUSTOMER_ACCOUNT_SHOP_ID: z.string().min(1),
  EXPO_PUBLIC_BACKEND_BASE_URL: z.string().url().optional(),
});

export const env = envSchema.parse({
  EXPO_PUBLIC_STORE_DOMAIN: process.env.EXPO_PUBLIC_STORE_DOMAIN,
  EXPO_PUBLIC_STORE_TOKEN: process.env.EXPO_PUBLIC_STORE_TOKEN,
  EXPO_PUBLIC_ENCRYPTION_KEY: process.env.EXPO_PUBLIC_ENCRYPTION_KEY,
  EXPO_PUBLIC_CUSTOMER_STORE_ENDPOINT:
    process.env.EXPO_PUBLIC_CUSTOMER_STORE_ENDPOINT,
  EXPO_PUBLIC_CUSTOMER_ACCOUNT_API_TOKEN:
    process.env.EXPO_PUBLIC_CUSTOMER_ACCOUNT_API_TOKEN,
  EXPO_PUBLIC_CUSTOMER_ACCOUNT_API_ENDPOINT:
    process.env.EXPO_PUBLIC_CUSTOMER_ACCOUNT_API_ENDPOINT,
  EXPO_PUBLIC_CUSTOMER_ACCOUNT_SHOP_ID:
    process.env.EXPO_PUBLIC_CUSTOMER_ACCOUNT_SHOP_ID,
  EXPO_PUBLIC_BACKEND_BASE_URL: process.env.EXPO_PUBLIC_BACKEND_BASE_URL,
});
